/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
static yyconst short int yy_accept[262] =
    {   0,
        0,    0,    0,    0,   68,   66,   65,   64,   38,   66,
       46,   57,   66,   47,   48,   32,   30,   55,   31,   54,
       33,   60,   60,   53,   42,   56,   41,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   49,   50,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   51,   66,   52,
        4,    6,    5,   65,   40,    0,   63,   37,    0,    0,
       45,   34,   35,   61,    2,    1,    0,   60,   44,   39,
       43,   59,   59,    0,   59,   59,   59,   59,   59,   28,
       59,   59,   27,   59,   10,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       28,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   36,    4,    3,   62,    0,
        1,    0,    0,   58,   59,   59,   59,   59,   59,   59,
       59,   59,   13,    8,   59,   59,   59,   59,   59,   59,
       25,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,    8,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   58,   29,   59,    7,   14,   59,   59,   11,   59,
       59,   59,   59,   59,   59,   24,   59,   59,   59,   29,
       59,    7,   14,   59,   59,   59,   59,   22,   59,   59,

       59,   59,   59,   59,   59,   59,   15,   59,   59,   59,
       59,   23,   59,   59,   59,   59,   59,   59,   12,   18,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   16,    9,   26,
       21,   19,   59,   59,   59,   59,   59,   59,   29,   59,
       59,   17,   20,    8,   59,   59,   59,   14,   59,    7,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    7,   21,   22,
       23,   24,    7,    7,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   34,
       34,   40,   41,   42,   43,   44,   45,   34,   46,   34,
       47,   48,   49,    7,    7,    7,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   34,   59,   60,   61,   62,
       63,   34,   34,   64,   65,   66,   67,   68,   69,   34,
       70,   34,   71,   72,   73,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[74] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    4,    3,    3,    3,    3,    3,    5,    5,
        3,    3,    3,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    3,    3,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        3,    3,    3
    } ;

static yyconst short int yy_base[270] =
    {   0,
        0,    0,   71,   72,  247, 1122,   74, 1122,  223,  223,
     1122,  213,  165, 1122, 1122,  193,  185, 1122,  181,   60,
       64,   69,   73, 1122,  173,  172,  163,   75,   77,   79,
       81,   83,  112,   95,  115,  119,   89,  127,  129,  121,
      136, 1122, 1122,  138,  151,  153,  158,  162,  168,  170,
      172,  174,  184,  191,  208,  214,  216, 1122,  112, 1122,
        0, 1122,  162,   79, 1122,  173,  169, 1122,  157,  227,
     1122, 1122, 1122,   85, 1122,    0,   87,  222, 1122, 1122,
     1122,  116,  225,   74,  230,  237,  240,  232,  256,  277,
      261,  279,  281,  285,  287,  291,  293,  298,  301,  310,

      303,  332,  334,  336,  341,  339,  343,  345,  347,  352,
      356,  358,  365,  381,  391,  394,  396,  399,  401,  411,
      407,  413,  416,  420,  430, 1122,    0, 1122, 1122,  150,
        0,   78,   96,   64,  436,  451,  462,  466,  468,  470,
      472,  475,  477,  485,  480,  487,  492,  501,  509,  511,
      516,  525,  530,  522,  533,  527,  540,  545,  551,  556,
      565,  569,  574,  577,  581,  585,  588,  594,  598,  600,
      606,   63,  620,  636,  638,  631,  649,  642,  653,  655,
      657,  661,  667,  671,  678,  674,  687,  691,  696,  693,
      703,  707,  711,  713,  716,  725,  729,  736,  745,  747,

      751,  754,  767,  769,  771,  780,  783,  792,  802,  806,
      809,  814,  816,  824,  828,  835,  832,  839,  848,  850,
      853,  857,  864,  868,  870,  873,  882,  886,  894,  888,
      899,  911,  918,  923,  932,  928,  936,  934,  942,  948,
      952,  958,  965,  967,  971,  973,  977,  981,  983,  987,
      990, 1002, 1006, 1012, 1016, 1021, 1024, 1027, 1031, 1035,
     1122, 1095, 1098, 1101,   86, 1106, 1111,   82, 1116
    } ;

static yyconst short int yy_def[270] =
    {   0,
      261,    1,  262,  262,  261,  261,  261,  261,  261,  263,
      261,  261,  264,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  261,  261,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  261,  261,  261,
      266,  261,  261,  261,  261,  263,  263,  261,  261,  261,
      261,  261,  261,  261,  261,  267,  261,  261,  261,  261,
      261,  268,  265,  269,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  261,  266,  261,  261,  261,
      267,  269,  269,  269,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  269,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
        0,  261,  261,  261,  261,  261,  261,  261,  261
    } ;

static yyconst short int yy_nxt[1196] =
    {   0,
        6,    7,    8,    7,    9,   10,    6,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       28,   28,   34,   28,   28,   28,   28,   28,   28,   35,
       36,   37,   38,   39,   40,   41,   42,    6,   43,   28,
       44,   45,   46,   47,   48,   28,   28,   49,   28,   28,
       50,   28,   28,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   62,   62,   64,   75,   64,   74,   74,
       64,   76,   64,   63,   63,   77,   82,   78,   78,   77,
       83,   78,   78,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   82,   74,   74,   74,   74,   82,   82,   89,
       87,  134,  134,   82,   82,   85,   86,   88,   91,   90,
      133,   84,  134,   84,   95,   84,  134,   84,  101,   84,
       82,   82,   96,   82,   82,   84,   92,   82,   82,   82,
       82,   84,  133,   97,  172,   82,   82,   82,   82,   93,
       94,   98,  104,  103,   82,   82,   82,   82,   84,  129,
       99,   84,   84,  100,  102,   84,  129,   84,  105,   82,
       82,   82,   82,   84,   67,   84,   82,   82,   67,  128,
       82,   82,   84,  126,   84,   81,   82,   82,   82,   82,
       82,   82,   82,   82,   80,   79,   73,   84,   72,   84,

      106,  107,   82,   82,   84,   71,  110,  108,   84,   82,
       82,  113,   70,  109,   84,  111,   84,  112,   84,  116,
       84,   68,   95,   93,  114,  117,   82,   82,   67,  115,
       84,  118,   82,   82,   82,   82,  129,   84,   77,  119,
       78,   78,  120,   82,   82,   65,  261,  121,   82,   82,
       82,   82,  122,  261,   84,   82,   82,  123,   82,   82,
       84,  261,   84,  261,  137,  136,  261,  261,  135,  138,
      124,   84,  261,  125,   82,   82,   84,  130,   84,   82,
       82,  130,  261,   84,  261,  139,   84,  261,  130,  261,
      130,  261,  130,  261,  130,   82,   82,   82,   82,   82,

       82,  141,   84,   82,   82,   82,   82,   84,  261,   82,
       82,   82,   82,  261,  142,  261,   82,   82,  140,   82,
       82,   82,   82,   84,  143,   84,  261,   84,   82,   82,
      261,   84,  144,   84,  145,  146,  261,   84,  261,   84,
      147,  261,  148,  261,   84,  149,  261,   84,  261,   84,
       82,   82,   82,   82,   82,   82,   84,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,  150,  152,  153,
       82,   82,  261,  151,   82,   82,   82,   82,   84,  261,
       84,  261,   84,   82,   82,   84,  261,   84,  261,   84,
      261,   84,  261,   84,  156,  261,  155,  261,   84,   82,

       82,  154,   84,  261,   84,  261,  158,  261,  157,   82,
       82,   84,   82,   82,   82,   82,  261,   82,   82,   82,
       82,  159,  160,  261,  161,   82,   82,   84,  261,   82,
       82,   82,   82,  261,   82,   82,  261,   84,   82,   82,
       84,  261,   84,  261,  143,   84,  261,   84,   82,   82,
      261,  163,  261,   84,   82,   82,  162,   84,  261,   84,
      165,  164,   84,  261,  166,  261,   84,  261,  167,   82,
       82,  173,  169,  168,  261,  174,   84,  170,  261,  151,
       82,   82,   84,  171,   82,   82,   82,   82,   82,   82,
       82,   82,  177,   82,   82,   82,   82,   84,   82,   82,

      179,  175,  178,   82,   82,   82,   82,  176,   84,  261,
       82,   82,   84,  181,   84,  180,   84,  183,   84,   82,
       82,   84,  182,   84,  184,  261,   84,   82,   82,   82,
       82,   84,  261,   84,   82,   82,  261,  186,   84,  187,
       82,   82,  185,   82,   82,   82,   82,   84,   82,   82,
      261,   82,   82,  261,  261,   84,  261,   84,   82,   82,
      188,  261,   84,   82,   82,  189,  261,  261,   84,   82,
       82,   84,  261,   84,   82,   82,   84,  261,  261,   84,
      261,  190,  191,   82,   82,  261,   84,   82,   82,  261,
      192,   84,   82,   82,  194,   82,   82,   84,  261,   82,

       82,  261,   84,   82,   82,  193,   82,   82,  195,  179,
      261,   84,   82,   82,  261,   84,   82,   82,   82,   82,
       84,  261,  197,   84,   82,   82,  261,   84,  261,  196,
      261,   84,  261,  261,   84,  198,  200,  261,   82,   82,
       84,  261,  201,  199,   84,  261,   84,  186,  206,   82,
       82,  203,   84,  202,   82,   82,   82,   82,  261,  204,
       82,   82,  208,  209,  261,  205,   84,   82,   82,  261,
      207,   82,   82,   82,   82,   82,   82,   84,  211,   82,
       82,  261,   84,  212,   84,   82,   82,  213,   84,   82,
       82,  210,   82,   82,  261,   84,   82,   82,  261,   84,

      214,   84,  215,   84,  217,   82,   82,   84,  216,   82,
       82,   82,   82,   84,   82,   82,  261,   84,  261,  219,
       84,   82,   82,  220,   84,   82,   82,  218,  261,   82,
       82,   82,   82,   84,   82,   82,  261,   84,  261,   84,
      261,  261,   84,   82,   82,  261,  221,   82,   82,   84,
      261,  261,  261,   84,   82,   82,  222,   84,  261,   84,
      261,  207,   84,   82,   82,   82,   82,  261,  223,   82,
       82,   84,   82,   82,  261,   84,  225,  261,  212,  224,
      261,  261,   84,  261,  226,   82,   82,   82,   82,   82,
       82,   84,  261,   84,  261,  261,  261,   84,   82,   82,

       84,   82,   82,  261,  232,  230,  228,  261,  227,  261,
       82,   82,  229,   84,  261,   84,  261,   84,  233,  261,
       82,   82,  219,  220,   82,   82,   84,   82,   82,   84,
      261,  231,   82,   82,   82,   82,  261,  236,   84,  234,
      261,  235,   82,   82,  237,  261,   82,   82,   84,  261,
       82,   82,   84,   82,   82,   84,  239,   82,   82,  261,
       84,  238,   84,  241,  261,  240,   82,   82,   82,   82,
       84,   82,   82,  261,   84,   82,   82,  261,   84,  242,
      261,   84,   82,   82,  261,   84,   82,   82,   82,   82,
      261,   82,   82,  261,   84,  261,   84,  261,  261,   84,

       82,   82,  243,   84,   82,   82,   82,   82,  244,  261,
       84,  261,   82,   82,   84,  261,   84,   82,   82,   84,
      261,  261,  261,  247,  261,  245,  248,  246,   84,   82,
       82,  261,   84,  261,   84,  261,   82,   82,  261,  239,
       84,   82,   82,  238,  241,   84,   82,   82,  249,  240,
       82,   82,   82,   82,   82,   82,  261,   84,  261,  250,
       82,   82,  261,  242,   84,  251,   82,   82,  253,   84,
       82,   82,  261,  252,   84,  254,   82,   82,   84,  261,
       84,  261,   84,   82,   82,   82,   82,  261,   84,   82,
       82,   82,   82,  261,   84,   82,   82,  261,   84,   82,

       82,   82,   82,  261,   84,   82,   82,  261,   82,   82,
      261,   84,  261,   84,  261,  257,  261,   84,  258,   84,
       82,   82,  261,   84,   82,   82,  249,   84,  261,   84,
       82,   82,  255,   84,   82,   82,   84,  256,  252,   82,
       82,  253,   82,   82,  254,   82,   82,  261,   84,   82,
       82,  261,   84,   82,   82,  261,  261,  261,   84,  261,
      261,  261,   84,  260,  261,  261,  261,   84,  261,  259,
       84,  261,  261,   84,  258,  261,  261,   84,  261,  261,
      261,   84,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  260,   61,   61,   61,   61,   61,

       66,   66,   66,   69,   69,   69,  127,  261,  127,  261,
      127,  131,  261,  131,  131,  131,  132,  261,  132,  132,
      132,    5,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261

    } ;

static yyconst short int yy_chk[1196] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    7,   21,    7,   20,   20,
       64,   21,   64,    3,    4,   22,  268,   22,   22,   23,
      265,   23,   23,   28,   28,   29,   29,   30,   30,   31,

       31,   32,   32,   74,   74,   77,   77,   37,   37,   31,
       30,  172,  134,   34,   34,   29,   29,   30,   32,   31,
       84,   28,   84,   29,   34,   30,  132,   31,   37,   32,
       33,   33,   34,   35,   35,   37,   33,   36,   36,   40,
       40,   34,  133,   35,  133,   38,   38,   39,   39,   33,
       33,   36,   40,   39,   41,   41,   44,   44,   33,  130,
       36,   35,   82,   36,   38,   36,   69,   40,   41,   45,
       45,   46,   46,   38,   67,   39,   47,   47,   66,   63,
       48,   48,   41,   59,   44,   27,   49,   49,   50,   50,
       51,   51,   52,   52,   26,   25,   19,   45,   17,   46,

       44,   44,   53,   53,   47,   16,   46,   45,   48,   54,
       54,   48,   13,   45,   49,   46,   50,   47,   51,   50,
       52,   12,   49,   48,   48,   51,   55,   55,   10,   49,
       53,   52,   56,   56,   57,   57,   70,   54,   78,   52,
       78,   78,   52,   83,   83,    9,    5,   53,   85,   85,
       88,   88,   54,    0,   55,   86,   86,   55,   87,   87,
       56,    0,   57,    0,   87,   86,    0,    0,   85,   88,
       56,   83,    0,   57,   89,   89,   85,   70,   88,   91,
       91,   70,    0,   86,    0,   89,   87,    0,   70,    0,
       70,    0,   70,    0,   70,   90,   90,   92,   92,   93,

       93,   91,   89,   94,   94,   95,   95,   91,    0,   96,
       96,   97,   97,    0,   92,    0,   98,   98,   90,   99,
       99,  101,  101,   90,   94,   92,    0,   93,  100,  100,
        0,   94,   96,   95,   97,   98,    0,   96,    0,   97,
       99,    0,  100,    0,   98,  101,    0,   99,    0,  101,
      102,  102,  103,  103,  104,  104,  100,  106,  106,  105,
      105,  107,  107,  108,  108,  109,  109,  102,  104,  105,
      110,  110,    0,  103,  111,  111,  112,  112,  102,    0,
      103,    0,  104,  113,  113,  106,    0,  105,    0,  107,
        0,  108,    0,  109,  108,    0,  107,    0,  110,  114,

      114,  106,  111,    0,  112,    0,  110,    0,  109,  115,
      115,  113,  116,  116,  117,  117,    0,  118,  118,  119,
      119,  111,  112,    0,  113,  121,  121,  114,    0,  120,
      120,  122,  122,    0,  123,  123,    0,  115,  124,  124,
      116,    0,  117,    0,  114,  118,    0,  119,  125,  125,
        0,  116,    0,  121,  135,  135,  115,  120,    0,  122,
      118,  117,  123,    0,  119,    0,  124,    0,  120,  136,
      136,  135,  122,  121,    0,  136,  125,  124,    0,  123,
      137,  137,  135,  125,  138,  138,  139,  139,  140,  140,
      141,  141,  139,  142,  142,  143,  143,  136,  145,  145,

      141,  137,  140,  144,  144,  146,  146,  138,  137,    0,
      147,  147,  138,  144,  139,  142,  140,  146,  141,  148,
      148,  142,  145,  143,  147,    0,  145,  149,  149,  150,
      150,  144,    0,  146,  151,  151,    0,  149,  147,  150,
      154,  154,  148,  152,  152,  156,  156,  148,  153,  153,
        0,  155,  155,    0,    0,  149,    0,  150,  157,  157,
      152,    0,  151,  158,  158,  153,    0,    0,  154,  159,
      159,  152,    0,  156,  160,  160,  153,    0,    0,  155,
        0,  154,  155,  161,  161,    0,  157,  162,  162,    0,
      156,  158,  163,  163,  158,  164,  164,  159,    0,  165,

      165,    0,  160,  166,  166,  157,  167,  167,  159,  160,
        0,  161,  168,  168,    0,  162,  169,  169,  170,  170,
      163,    0,  162,  164,  171,  171,    0,  165,    0,  161,
        0,  166,    0,    0,  167,  163,  165,    0,  173,  173,
      168,    0,  166,  164,  169,    0,  170,  168,  173,  176,
      176,  169,  171,  167,  174,  174,  175,  175,    0,  170,
      178,  178,  175,  176,    0,  171,  173,  177,  177,    0,
      174,  179,  179,  180,  180,  181,  181,  176,  178,  182,
      182,    0,  174,  180,  175,  183,  183,  181,  178,  184,
      184,  177,  186,  186,    0,  177,  185,  185,    0,  179,

      182,  180,  183,  181,  185,  187,  187,  182,  184,  188,
      188,  190,  190,  183,  189,  189,    0,  184,    0,  188,
      186,  191,  191,  189,  185,  192,  192,  187,    0,  193,
      193,  194,  194,  187,  195,  195,    0,  188,    0,  190,
        0,    0,  189,  196,  196,    0,  190,  197,  197,  191,
        0,    0,    0,  192,  198,  198,  192,  193,    0,  194,
        0,  191,  195,  199,  199,  200,  200,    0,  193,  201,
      201,  196,  202,  202,    0,  197,  195,    0,  196,  194,
        0,    0,  198,    0,  197,  203,  203,  204,  204,  205,
      205,  199,    0,  200,    0,    0,    0,  201,  206,  206,

      202,  207,  207,    0,  206,  202,  200,    0,  199,    0,
      208,  208,  201,  203,    0,  204,    0,  205,  208,    0,
      209,  209,  204,  205,  210,  210,  206,  211,  211,  207,
        0,  203,  212,  212,  213,  213,    0,  211,  208,  209,
        0,  210,  214,  214,  213,    0,  215,  215,  209,    0,
      217,  217,  210,  216,  216,  211,  215,  218,  218,    0,
      212,  214,  213,  217,    0,  216,  219,  219,  220,  220,
      214,  221,  221,    0,  215,  222,  222,    0,  217,  218,
        0,  216,  223,  223,    0,  218,  224,  224,  225,  225,
        0,  226,  226,    0,  219,    0,  220,    0,    0,  221,

      227,  227,  221,  222,  228,  228,  230,  230,  222,    0,
      223,    0,  229,  229,  224,    0,  225,  231,  231,  226,
        0,    0,    0,  225,    0,  223,  226,  224,  227,  232,
      232,    0,  228,    0,  230,    0,  233,  233,    0,  228,
      229,  234,  234,  227,  230,  231,  236,  236,  232,  229,
      235,  235,  238,  238,  237,  237,    0,  232,    0,  233,
      239,  239,    0,  231,  233,  234,  240,  240,  236,  234,
      241,  241,    0,  235,  236,  237,  242,  242,  235,    0,
      238,    0,  237,  243,  243,  244,  244,    0,  239,  245,
      245,  246,  246,    0,  240,  247,  247,    0,  241,  248,

      248,  249,  249,    0,  242,  250,  250,    0,  251,  251,
        0,  243,    0,  244,    0,  250,    0,  245,  251,  246,
      252,  252,    0,  247,  253,  253,  243,  248,    0,  249,
      254,  254,  244,  250,  255,  255,  251,  245,  246,  256,
      256,  247,  257,  257,  248,  258,  258,    0,  252,  259,
      259,    0,  253,  260,  260,    0,    0,    0,  254,    0,
        0,    0,  255,  257,    0,    0,    0,  256,    0,  255,
      257,    0,    0,  258,  256,    0,    0,  259,    0,    0,
        0,  260,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  259,  262,  262,  262,  262,  262,

      263,  263,  263,  264,  264,  264,  266,    0,  266,    0,
      266,  267,    0,  267,  267,  267,  269,    0,  269,  269,
      269,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "wardenlex.l"
#define INITIAL 0
#line 4 "wardenlex.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    int lineno = 1;
    int words = 0;
    void ret_print(char *token_type);
    void yyerror();
    void ret_commt();
    char str[20];
   
#define ML_COMMENT 1

#line 732 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 30 "wardenlex.l"


#line 886 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 262 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1122 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "wardenlex.l"
{ ret_commt("Line is commented at line %d\n", lineno); } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "wardenlex.l"
{ ret_commt("Start of comment from line %d\n", lineno); BEGIN(ML_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "wardenlex.l"
{ ret_commt("Ends to line %d\n", lineno); BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "wardenlex.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "wardenlex.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "wardenlex.l"
{ lineno += 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "wardenlex.l"
{ ret_print("KEYWORD_CHAR"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "wardenlex.l"
{ ret_print("KEYWORD_INT"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "wardenlex.l"
{ ret_print("KEYWORD_SINGLE"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "wardenlex.l"
{ ret_print("KEYWORD_IF"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "wardenlex.l"
{ ret_print("KEYWORD_ELSE"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "wardenlex.l"
{ ret_print("KEYWORD_WHILE"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "wardenlex.l"
{ ret_print("KEYWORD_FOR"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "wardenlex.l"
{ ret_print("KEYWORD_CONTINUE"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "wardenlex.l"
{ ret_print("KEYWORD_BREAK"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "wardenlex.l"
{ ret_print("KEYWORD_RETURN"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "wardenlex.l"
{ ret_print("KEYWORD_DEFAULT"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "wardenlex.l"
{ ret_print("KEYWORD_YIELD"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "wardenlex.l"
{ ret_print("KEYWORD_UNLESS"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "wardenlex.l"
{ ret_print("KEYWORD_DOTIMES"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "wardenlex.l"
{ ret_print("KEYWORD_SWITCH"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "wardenlex.l"
{ ret_print("RESWORD_MAIN"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "wardenlex.l"
{ ret_print("RESWORD_FALSE"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "wardenlex.l"
{ ret_print("RESWORD_TRUE"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "wardenlex.l"
{ ret_print("KEYWORD_VAR"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "wardenlex.l"
{ ret_print("KEYWORD_STRING"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "wardenlex.l"
{ ret_print("KEYWORD_FUNCTION"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "wardenlex.l"
{ ret_print("KEYWORD_DO"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "wardenlex.l"
{ ret_print("KEYWORD_BOOL"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "wardenlex.l"
{ ret_print("MINOP"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "wardenlex.l"
{ ret_print("ADDOP"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "wardenlex.l"
{ ret_print("MULOP"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "wardenlex.l"
{ ret_print("DIVOP"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "wardenlex.l"
{ ret_print("IINCROP"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "wardenlex.l"
{ ret_print("DINCROP"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "wardenlex.l"
{ ret_print("OROP"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "wardenlex.l"
{ ret_print("ANDOP"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "wardenlex.l"
{ ret_print("NOTOP"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 76 "wardenlex.l"
{ ret_print("EQUOP"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 77 "wardenlex.l"
{ ret_print("NOTEQUOP"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 78 "wardenlex.l"
{ ret_print("GTHANOP"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 79 "wardenlex.l"
{ ret_print("LTHANOP"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 80 "wardenlex.l"
{ ret_print("GEQTHANOP"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 81 "wardenlex.l"
{ ret_print("LEQTHANOP"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "wardenlex.l"
{ ret_print("EXPOP"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "wardenlex.l"
{ ret_print("MODOP"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "wardenlex.l"
{ ret_print("LPAREN"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "wardenlex.l"
{ ret_print("RPAREN"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "wardenlex.l"
{ ret_print("LBRACK"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "wardenlex.l"
{ ret_print("RBRACK"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "wardenlex.l"
{ ret_print("LBRACE"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "wardenlex.l"
{ ret_print("RBRACE"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "wardenlex.l"
{ ret_print("SEMI"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "wardenlex.l"
{ ret_print("DOT"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "wardenlex.l"
{ ret_print("COMMA"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "wardenlex.l"
{ ret_print("ASSIGN"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "wardenlex.l"
{ ret_print("REFER"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "wardenlex.l"
{ ret_print("ARRAY"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "wardenlex.l"
{ ret_print("ID"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "wardenlex.l"
{ ret_print("ICONST"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "wardenlex.l"
{ ret_print("FCONST"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "wardenlex.l"
{ ret_print("CCONST"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "wardenlex.l"
{ ret_print("STRING"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "wardenlex.l"
{ lineno += 1; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "wardenlex.l"
;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "wardenlex.l"
{ yyerror("INVALID"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "wardenlex.l"
ECHO;
	YY_BREAK
#line 1304 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 262 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 262 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 261);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 109 "wardenlex.l"

 
void ret_print(char *token_type){
    words++;
    printf("Lexemes: %s\tToken: %s\tLineNo: %d\n", yytext, token_type, lineno);
    fprintf(yyout,"Lexeme: %s\tToken: %s\tLineNo: %d\n",yytext, token_type, lineno);
}
 
void yyerror(char *message){
    printf("Error: \"%s\" in line %d. Token = %s\n", message, lineno, yytext);
    fprintf(yyout,"Error: \"%s\" in line %d. Lexeme = %s\n", message, lineno, yytext);
}

void ret_commt(char *message, int lineno){
    printf(message, lineno);
    fprintf(yyout, message, lineno);
}

 
int main(){
    extern FILE *yyin, *yyout; 

    printf("Enter Warden Source File:\n");
    scanf("%123s",str);
    strcat(str,".wd");
    yyin = fopen(str, "r"); 
    yyout = fopen("Symbol Table.txt", "w+"); 
    yylex();
    printf("\n\nTotal Tokens = %d", words);
	fprintf(yyout,"\n\n\nTotal Tokens = %d",words);

    return 1;
}