/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
static yyconst short int yy_accept[231] =
    {   0,
       56,   56,    0,    0,   60,   58,   57,   56,   36,   58,
       50,   49,   58,   39,   40,   31,   30,   47,   30,   46,
       32,   52,   52,   45,   38,   48,   38,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   41,   42,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   43,   58,   44,
        4,    6,    5,   57,   56,   37,    0,   55,   50,   35,
        0,    0,   33,   53,    2,    1,    0,   52,   38,   51,
       51,   51,   51,   51,   51,   51,   28,   51,   51,   27,
       51,   10,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   28,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   34,    4,    3,   54,    0,    1,   51,   51,
       51,   51,   51,   51,   51,   51,   13,    8,   51,   51,
       51,   51,   51,   51,   25,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   29,   51,    7,   51,   51,   51,
       11,   51,   51,   51,   51,   51,   24,   51,   51,   51,
       51,   51,   51,   51,   51,   22,   51,   51,   51,   51,
       51,   51,   51,   15,   51,   51,   51,   23,   51,   51,

       51,   51,   51,   12,   18,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   16,    9,   26,   21,
       19,   51,   51,   51,   51,   17,   20,   51,   14,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    8,   21,   22,
       23,   24,    8,    8,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   34,
       34,   40,   41,   42,   43,   44,   45,   34,   46,   34,
       47,   48,   49,    8,    8,    8,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   34,   59,   60,   61,   62,
       63,   34,   34,   64,   65,   66,   67,   68,   69,   34,
       70,   34,   71,   72,   73,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[74] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    4,    3,    3,    3,    3,    3,    5,    5,
        3,    3,    3,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    3,    3,    3,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        3,    3,    3
    } ;

static yyconst short int yy_base[239] =
    {   0,
        0,    0,   71,   72,  233,  736,   74,  226,  204,  218,
        0,  209,  159,  736,  736,  736,  181,  736,  170,   60,
       64,   69,   73,  736,  154,  150,  147,   75,   77,   79,
       81,   83,   87,   85,  102,   94,   89,  113,  115,  118,
      122,  736,  736,  124,  126,  128,  133,  140,  137,  144,
      142,  146,  149,  152,  155,  159,  161,  736,   95,  736,
        0,  736,  140,   79,  151,  736,  143,  124,    0,  736,
      118,  166,  736,  165,  736,    0,  178,  189,  736,    0,
      181,  203,  191,  206,  216,  218,  220,  224,  227,  230,
      232,  236,  238,  240,  247,  249,  251,  254,  256,  258,

      267,  274,  271,  276,  282,  285,  287,  289,  291,  293,
      295,  297,  299,  301,  303,  305,  308,  316,  318,  320,
      324,  326,  736,    0,  736,  736,  114,    0,  332,  329,
      341,  351,  354,  356,  366,  368,  371,  377,  379,  381,
      383,  385,  388,  391,  394,  399,  404,  406,  409,  411,
      413,  417,  419,  422,  424,  426,  428,  430,  432,  434,
      437,  442,  444,  449,  451,  462,  453,  465,  473,  482,
      486,  488,  491,  493,  495,  501,  503,  505,  507,  515,
      518,  520,  522,  525,  528,  530,  532,  534,  536,  538,
      540,  543,  546,  548,  550,  555,  552,  560,  564,  581,

      573,  587,  589,  592,  594,  596,  601,  598,  603,  605,
      607,  609,  612,  614,  618,  621,  616,  623,  625,  627,
      629,  631,  634,  636,  649,  651,  653,  655,  660,  736,
      709,  712,  717,  720,   86,  725,  730,   82
    } ;

static yyconst short int yy_def[239] =
    {   0,
      230,    1,  231,  231,  230,  230,  230,  230,  230,  232,
      233,  230,  234,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  230,  230,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  230,  230,  230,
      236,  230,  230,  230,  230,  230,  232,  232,  233,  230,
      230,  230,  230,  230,  230,  237,  230,  230,  230,  238,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  230,  236,  230,  230,  230,  237,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,    0,
      230,  230,  230,  230,  230,  230,  230,  230
    } ;

static yyconst short int yy_nxt[810] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,    6,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       28,   28,   34,   28,   28,   28,   28,   28,   28,   35,
       36,   37,   38,   39,   40,   41,   42,    6,   43,   28,
       44,   45,   46,   47,   48,   28,   28,   49,   28,   28,
       50,   28,   28,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   62,   62,   64,   75,   64,   74,   74,
       64,   76,   64,   63,   63,   77,   80,   78,   78,   77,
       81,   78,   78,   80,   80,   80,   80,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   80,   80,   86,
       84,   89,   80,   80,   92,   82,   83,   85,   88,   87,
       80,   80,   93,  126,   90,   91,   95,  126,   98,   68,
       94,   80,   80,   80,   80,   96,   80,   80,   97,  100,
       80,   80,   80,   80,   80,   80,   80,   80,   68,  101,
       99,   80,   80,   65,  102,   80,   80,  125,   80,   80,
       80,   80,   80,   80,   80,   80,  123,   80,   80,   79,
       80,   80,   66,   80,   80,  126,   79,   80,   80,   80,
       80,  107,  105,   74,   74,   73,  103,  104,  106,  110,
      108,   92,  109,  113,   73,  114,   74,   74,  112,   80,

       80,   90,  111,  115,  120,   77,   72,   78,   78,   80,
       80,  116,  118,  119,  117,  121,  127,   70,  122,  130,
      127,   80,   80,   68,   80,   80,   66,  127,   65,  127,
      131,  127,  230,  127,   80,   80,   80,   80,   80,   80,
      230,  129,   80,   80,  230,   80,   80,  133,   80,   80,
       80,   80,  230,  132,   80,   80,   80,   80,   80,   80,
      230,  134,  136,  230,  135,   80,   80,   80,   80,   80,
       80,  137,   80,   80,   80,   80,   80,   80,  230,  138,
      230,  139,  230,  142,  140,   80,   80,  230,  141,   80,
       80,  144,   80,   80,   80,   80,  143,  145,  230,  146,

       80,   80,  147,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,  230,   80,   80,  230,  149,
      230,  150,  230,  148,   80,   80,   80,   80,   80,   80,
      230,  152,   80,   80,   80,   80,  151,   80,   80,  230,
       80,   80,  155,  166,  153,  154,  156,  230,  137,   80,
       80,  230,  138,  230,  158,  160,  157,  165,  159,   80,
       80,  230,   80,   80,   80,   80,  230,  162,  169,  164,
      167,  163,  161,  145,   80,   80,   80,   80,  170,   80,
       80,  230,  168,  230,  171,   80,   80,   80,   80,   80,

       80,   80,   80,   80,   80,  230,   80,   80,  172,   80,
       80,  174,   80,   80,  230,  175,  177,   80,   80,  178,
      230,  173,   80,   80,   80,   80,  176,   80,   80,   80,
       80,   80,   80,  230,  179,   80,   80,   80,   80,  180,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,  230,   80,   80,  230,  181,  230,
       80,   80,   80,   80,  230,  165,  183,   80,   80,   80,
       80,   80,   80,  230,  167,  171,  184,  230,  182,  230,
       80,   80,  230,   80,   80,  188,  230,  186,  185,  189,
      177,   80,   80,  230,  187,  191,  194,  195,  230,  190,

       80,   80,  230,  192,   80,   80,   80,   80,  193,   80,
       80,   80,   80,   80,   80,  196,  198,  230,  197,   80,
       80,   80,   80,   80,   80,   80,   80,  202,  200,  230,
      199,  230,  201,   80,   80,  204,   80,   80,   80,   80,
       80,   80,  205,   80,   80,  203,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
      230,   80,   80,  230,   80,   80,   80,   80,   80,   80,
       80,   80,  230,   80,   80,  230,  194,  206,   80,   80,
      216,  198,   80,   80,  230,  208,  230,  214,  207,  212,
      215,   80,   80,  210,  230,  209,  204,  211,  205,   80,

       80,  217,  230,  219,  213,   80,   80,   80,   80,  218,
       80,   80,   80,   80,   80,   80,   80,   80,  220,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,  221,
       80,   80,   80,   80,   80,   80,   80,   80,  230,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,  224,   80,   80,   80,   80,  225,  222,  218,  226,
      223,  227,  219,  230,  217,  220,  230,   80,   80,   80,
       80,   80,   80,   80,   80,  230,  221,  229,   80,   80,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  228,  230,  226,

      227,  230,  230,  230,  230,  230,  230,  230,  229,   61,
       61,   61,   61,   61,   67,   67,   67,   69,  230,   69,
       69,   69,   71,   71,   71,  124,  230,  124,  230,  124,
      128,  230,  128,  128,  128,    5,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  230,  230,  230
    } ;

static yyconst short int yy_chk[810] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    7,   21,    7,   20,   20,
       64,   21,   64,    3,    4,   22,  238,   22,   22,   23,
      235,   23,   23,   28,   28,   29,   29,   30,   30,   31,

       31,   32,   32,   34,   34,   33,   33,   37,   37,   31,
       30,   33,   36,   36,   34,   29,   29,   30,   32,   31,
       35,   35,   34,  127,   33,   33,   36,   71,   37,   68,
       35,   38,   38,   39,   39,   36,   40,   40,   36,   39,
       41,   41,   44,   44,   45,   45,   46,   46,   67,   40,
       38,   47,   47,   65,   41,   49,   49,   63,   48,   48,
       51,   51,   50,   50,   52,   52,   59,   53,   53,   27,
       54,   54,   26,   55,   55,   72,   25,   56,   56,   57,
       57,   46,   45,   74,   74,   19,   44,   44,   45,   48,
       46,   49,   47,   50,   17,   51,   77,   77,   49,   81,

       81,   48,   48,   52,   55,   78,   13,   78,   78,   83,
       83,   52,   53,   54,   52,   56,   72,   12,   57,   83,
       72,   82,   82,   10,   84,   84,    9,   72,    8,   72,
       84,   72,    5,   72,   85,   85,   86,   86,   87,   87,
        0,   82,   88,   88,    0,   89,   89,   86,   90,   90,
       91,   91,    0,   85,   92,   92,   93,   93,   94,   94,
        0,   87,   89,    0,   88,   95,   95,   96,   96,   97,
       97,   91,   98,   98,   99,   99,  100,  100,    0,   93,
        0,   94,    0,   97,   95,  101,  101,    0,   96,  103,
      103,   99,  102,  102,  104,  104,   98,  100,    0,  101,

      105,  105,  102,  106,  106,  107,  107,  108,  108,  109,
      109,  110,  110,  111,  111,  112,  112,  113,  113,  114,
      114,  115,  115,  116,  116,    0,  117,  117,    0,  104,
        0,  105,    0,  103,  118,  118,  119,  119,  120,  120,
        0,  107,  121,  121,  122,  122,  106,  130,  130,    0,
      129,  129,  110,  130,  108,  109,  113,    0,  111,  131,
      131,    0,  112,    0,  115,  117,  114,  129,  116,  132,
      132,    0,  133,  133,  134,  134,    0,  119,  133,  122,
      131,  121,  118,  120,  135,  135,  136,  136,  134,  137,
      137,    0,  132,    0,  135,  138,  138,  139,  139,  140,

      140,  141,  141,  142,  142,    0,  143,  143,  136,  144,
      144,  140,  145,  145,    0,  141,  143,  146,  146,  144,
        0,  139,  147,  147,  148,  148,  142,  149,  149,  150,
      150,  151,  151,    0,  146,  152,  152,  153,  153,  147,
      154,  154,  155,  155,  156,  156,  157,  157,  158,  158,
      159,  159,  160,  160,    0,  161,  161,    0,  149,    0,
      162,  162,  163,  163,    0,  148,  152,  164,  164,  165,
      165,  167,  167,    0,  150,  154,  153,    0,  151,    0,
      166,  166,    0,  168,  168,  158,    0,  156,  155,  159,
      161,  169,  169,    0,  157,  162,  166,  168,    0,  160,

      170,  170,    0,  163,  171,  171,  172,  172,  164,  173,
      173,  174,  174,  175,  175,  169,  172,    0,  170,  176,
      176,  177,  177,  178,  178,  179,  179,  176,  174,    0,
      173,    0,  175,  180,  180,  179,  181,  181,  182,  182,
      183,  183,  180,  184,  184,  178,  185,  185,  186,  186,
      187,  187,  188,  188,  189,  189,  190,  190,  191,  191,
        0,  192,  192,    0,  193,  193,  194,  194,  195,  195,
      197,  197,    0,  196,  196,    0,  181,  182,  198,  198,
      197,  185,  199,  199,    0,  184,    0,  195,  183,  190,
      196,  201,  201,  188,    0,  187,  192,  189,  193,  200,

      200,  199,    0,  201,  191,  202,  202,  203,  203,  200,
      204,  204,  205,  205,  206,  206,  208,  208,  202,  207,
      207,  209,  209,  210,  210,  211,  211,  212,  212,  203,
      213,  213,  214,  214,  217,  217,  215,  215,    0,  216,
      216,  218,  218,  219,  219,  220,  220,  221,  221,  222,
      222,  208,  223,  223,  224,  224,  214,  206,  210,  215,
      207,  216,  211,    0,  209,  212,    0,  225,  225,  226,
      226,  227,  227,  228,  228,    0,  213,  225,  229,  229,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  222,    0,  223,

      224,    0,    0,    0,    0,    0,    0,    0,  228,  231,
      231,  231,  231,  231,  232,  232,  232,  233,    0,  233,
      233,  233,  234,  234,  234,  236,    0,  236,    0,  236,
      237,    0,  237,  237,  237,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  230,  230,  230
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "wardenlex.l"
#define INITIAL 0
#line 4 "wardenlex.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    int lineno = 1; // initialized number of line with 1
    int words = 0;  //number of lexemes
    void ret_print(char *token_type);
    void yyerror();
#define ML_COMMENT 1

#line 633 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 27 "wardenlex.l"


#line 787 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 231 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 736 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "wardenlex.l"
{ printf("Eat up comment at line %d\n", lineno); } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "wardenlex.l"
{ printf("Eat up comment from line %d ", lineno); BEGIN(ML_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "wardenlex.l"
{ printf("to line %d\n", lineno); BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "wardenlex.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "wardenlex.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "wardenlex.l"
{ lineno += 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "wardenlex.l"
{ ret_print("KEYWORD_CHAR"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "wardenlex.l"
{ ret_print("KEYWORD_INT"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "wardenlex.l"
{ ret_print("KEYWORD_SINGLE"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "wardenlex.l"
{ ret_print("KEYWORD_IF"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "wardenlex.l"
{ ret_print("KEYWORD_ELSE"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "wardenlex.l"
{ ret_print("KEYWORD_WHILE"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "wardenlex.l"
{ ret_print("KEYWORD_FOR"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "wardenlex.l"
{ ret_print("KEYWORD_CONTINUE"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "wardenlex.l"
{ ret_print("KEYWORD_BREAK"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "wardenlex.l"
{ ret_print("KEYWORD_RETURN"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "wardenlex.l"
{ ret_print("KEYWORD_DEFAULT"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "wardenlex.l"
{ ret_print("KEYWORD_YIELD"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "wardenlex.l"
{ ret_print("KEYWORD_UNLESS"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "wardenlex.l"
{ ret_print("KEYWORD_DOTIMES"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "wardenlex.l"
{ ret_print("KEYWORD_SWITCH"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "wardenlex.l"
{ ret_print("KEYWORD_MAIN"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "wardenlex.l"
{ ret_print("KEYWORD_FALSE"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "wardenlex.l"
{ ret_print("KEYWORD_TRUE"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "wardenlex.l"
{ ret_print("KEYWORD_VAR"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "wardenlex.l"
{ ret_print("KEYWORD_STRING"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "wardenlex.l"
{ ret_print("KEYWORD_FUNCTION"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "wardenlex.l"
{ ret_print("KEYWORD_DO"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "wardenlex.l"
{ ret_print("KEYWORD_BOOL"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "wardenlex.l"
{ ret_print("ADDOP"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "wardenlex.l"
{ ret_print("MULOP"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "wardenlex.l"
{ ret_print("DIVOP"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "wardenlex.l"
{ ret_print("INCR"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "wardenlex.l"
{ ret_print("OROP"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "wardenlex.l"
{ ret_print("ANDOP"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "wardenlex.l"
{ ret_print("NOTOP"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "wardenlex.l"
{ ret_print("EQUOP"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "wardenlex.l"
{ ret_print("RELOP"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "wardenlex.l"
{ ret_print("LPAREN"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "wardenlex.l"
{ ret_print("RPAREN"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "wardenlex.l"
{ ret_print("LBRACK"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "wardenlex.l"
{ ret_print("RBRACK"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "wardenlex.l"
{ ret_print("LBRACE"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "wardenlex.l"
{ ret_print("RBRACE"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "wardenlex.l"
{ ret_print("SEMI"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "wardenlex.l"
{ ret_print("DOT"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "wardenlex.l"
{ ret_print("COMMA"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "wardenlex.l"
{ ret_print("ASSIGN"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "wardenlex.l"
{ ret_print("REFER"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "wardenlex.l"
{ ret_print("PREPROCESSOR DIRECTIVES"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 88 "wardenlex.l"
{ ret_print("ID"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 89 "wardenlex.l"
{ ret_print("ICONST"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 90 "wardenlex.l"
{ ret_print("FCONST"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "wardenlex.l"
{ ret_print("CCONST"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "wardenlex.l"
{ ret_print("STRING"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "wardenlex.l"
{ lineno += 1; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "wardenlex.l"
/* eat up whitespace */
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "wardenlex.l"
{ yyerror("Unrecognized character"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "wardenlex.l"
ECHO;
	YY_BREAK
#line 1165 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 231 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 231 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 230);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 100 "wardenlex.l"

 
void ret_print(char *token_type){
    words++;
    printf("yytext: %s\ttoken: %s\tlineno: %d\n", yytext, token_type, lineno);
}
 
void yyerror(char *message){
    printf("Error: \"%s\" in line %d. Token = %s\n", message, lineno, yytext);
    exit(1);
}
 
int main(int argc, char *argv[]){
    yyin = fopen(argv[1], "r");
    yylex();
    fclose(yyin);
    printf("Number of Lexemes = %d\n", words);
    return 0;
}