/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
static yyconst short int yy_accept[236] =
    {   0,
       64,   64,    0,    0,   68,   66,   65,   64,   38,   66,
       58,   46,   57,   66,   47,   48,   32,   30,   55,   31,
       54,   33,   60,   60,   53,   42,   56,   41,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   49,   50,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   51,   66,
       52,    4,    6,    5,   65,   64,   40,    0,   63,   58,
       37,    0,    0,   45,   34,   35,   61,    2,    1,    0,
       60,   44,   39,   43,   59,   59,   59,   59,   59,   59,
       59,   28,   59,   59,   27,   59,   10,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   28,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   36,    4,    3,
       62,    0,    1,   59,   59,   59,   59,   59,   59,   59,
       59,   13,    8,   59,   59,   59,   59,   59,   59,   25,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   29,
       59,    7,   59,   59,   59,   11,   59,   59,   59,   59,
       59,   24,   59,   59,   59,   59,   59,   59,   59,   59,
       22,   59,   59,   59,   59,   59,   59,   59,   15,   59,

       59,   59,   23,   59,   59,   59,   59,   59,   12,   18,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   16,    9,   26,   21,   19,   59,   59,   59,   59,
       17,   20,   59,   14,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    8,   22,   23,
       24,   25,    8,    8,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   35,
       35,   41,   42,   43,   44,   45,   46,   35,   47,   35,
       48,   49,   50,    8,    8,    8,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   35,   60,   61,   62,   63,
       64,   35,   35,   65,   66,   67,   68,   69,   70,   35,
       71,   35,   72,   73,   74,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[75] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    3,    3,    3,    3,    3,    5,
        5,    3,    3,    3,    3,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    3,    3,    3,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    3,    3,    3
    } ;

static yyconst short int yy_base[244] =
    {   0,
        0,    0,   72,   73,  259,  734,   75,  248,  219,  233,
        0,  734,  221,  178,  734,  734,  211,  207,  734,  199,
       60,   64,   64,   70,  734,  181,  169,  160,   72,   74,
       76,   78,   80,   84,   82,   99,   91,   86,  110,  112,
      115,  119,  734,  734,  121,  123,  125,  130,  137,  134,
      141,  139,  143,  146,  149,  152,  156,  158,  734,  102,
      734,    0,  734,  152,  124,  165,  734,  159,  150,    0,
      734,  141,  163,  734,  734,  734,  162,  734,    0,  175,
      186,  734,  734,  734,    0,  178,  200,  188,  203,  213,
      215,  217,  221,  224,  227,  229,  233,  235,  237,  244,

      246,  248,  251,  253,  255,  264,  271,  268,  273,  279,
      282,  284,  286,  288,  290,  292,  294,  296,  298,  300,
      302,  305,  313,  315,  317,  321,  323,  734,    0,  734,
      734,  136,    0,  329,  326,  338,  348,  351,  353,  363,
      365,  368,  374,  376,  378,  380,  382,  385,  388,  391,
      396,  401,  403,  406,  408,  410,  414,  416,  419,  421,
      423,  425,  427,  429,  431,  434,  439,  441,  446,  448,
      459,  450,  462,  470,  479,  483,  485,  488,  490,  492,
      498,  500,  502,  504,  512,  515,  517,  519,  522,  525,
      527,  529,  531,  533,  535,  537,  540,  543,  545,  547,

      552,  549,  557,  561,  578,  570,  584,  586,  589,  591,
      593,  598,  595,  600,  602,  604,  606,  609,  611,  615,
      618,  613,  620,  622,  624,  626,  628,  631,  633,  646,
      648,  650,  652,  657,  734,  707,  710,  715,  718,  117,
      723,  728,   84
    } ;

static yyconst short int yy_def[244] =
    {   0,
      235,    1,  236,  236,  235,  235,  235,  235,  235,  237,
      238,  235,  235,  239,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  235,  235,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  235,  235,
      235,  241,  235,  235,  235,  235,  235,  237,  237,  238,
      235,  235,  235,  235,  235,  235,  235,  235,  242,  235,
      235,  235,  235,  235,  243,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  235,  241,  235,
      235,  235,  242,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,    0,  235,  235,  235,  235,  235,
      235,  235,  235
    } ;

static yyconst short int yy_nxt[809] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,    6,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   29,   29,   35,   29,   29,   29,   29,   29,   29,
       36,   37,   38,   39,   40,   41,   42,   43,    6,   44,
       29,   45,   46,   47,   48,   49,   29,   29,   50,   29,
       29,   51,   29,   29,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   63,   63,   65,   78,   65,   77,
       77,   80,   79,   81,   81,   64,   64,   80,   85,   81,
       81,   85,   85,   85,   85,   85,   85,   85,   85,   85,

       85,   85,   85,   85,   85,   85,   85,   91,   89,   94,
       85,   85,   97,   87,   88,   90,   93,   92,   85,   85,
       98,   86,   95,   96,  100,   65,  103,   65,   99,   85,
       85,   85,   85,  101,   85,   85,  102,  105,   85,   85,
       85,   85,   85,   85,   85,   85,  131,  106,  104,   85,
       85,  131,  107,   85,   85,   69,   85,   85,   85,   85,
       85,   85,   85,   85,   69,   85,   85,   66,   85,   85,
      130,   85,   85,  131,  128,   85,   85,   85,   85,  112,
      110,   77,   77,   84,  108,  109,  111,  115,  113,   97,
      114,  118,   83,  119,   77,   77,  117,   85,   85,   95,

      116,  120,  125,   80,   82,   81,   81,   85,   85,  121,
      123,  124,  122,  126,  132,   76,  127,  135,  132,   85,
       85,   75,   85,   85,   74,  132,   73,  132,  136,  132,
       71,  132,   85,   85,   85,   85,   85,   85,   69,  134,
       85,   85,   67,   85,   85,  138,   85,   85,   85,   85,
       66,  137,   85,   85,   85,   85,   85,   85,  235,  139,
      141,  235,  140,   85,   85,   85,   85,   85,   85,  142,
       85,   85,   85,   85,   85,   85,  235,  143,  235,  144,
      235,  147,  145,   85,   85,  235,  146,   85,   85,  149,
       85,   85,   85,   85,  148,  150,  235,  151,   85,   85,

      152,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,  235,   85,   85,  235,  154,  235,  155,
      235,  153,   85,   85,   85,   85,   85,   85,  235,  157,
       85,   85,   85,   85,  156,   85,   85,  235,   85,   85,
      160,  171,  158,  159,  161,  235,  142,   85,   85,  235,
      143,  235,  163,  165,  162,  170,  164,   85,   85,  235,
       85,   85,   85,   85,  235,  167,  174,  169,  172,  168,
      166,  150,   85,   85,   85,   85,  175,   85,   85,  235,
      173,  235,  176,   85,   85,   85,   85,   85,   85,   85,

       85,   85,   85,  235,   85,   85,  177,   85,   85,  179,
       85,   85,  235,  180,  182,   85,   85,  183,  235,  178,
       85,   85,   85,   85,  181,   85,   85,   85,   85,   85,
       85,  235,  184,   85,   85,   85,   85,  185,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,  235,   85,   85,  235,  186,  235,   85,   85,
       85,   85,  235,  170,  188,   85,   85,   85,   85,   85,
       85,  235,  172,  176,  189,  235,  187,  235,   85,   85,
      235,   85,   85,  193,  235,  191,  190,  194,  182,   85,
       85,  235,  192,  196,  199,  200,  235,  195,   85,   85,

      235,  197,   85,   85,   85,   85,  198,   85,   85,   85,
       85,   85,   85,  201,  203,  235,  202,   85,   85,   85,
       85,   85,   85,   85,   85,  207,  205,  235,  204,  235,
      206,   85,   85,  209,   85,   85,   85,   85,   85,   85,
      210,   85,   85,  208,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,  235,   85,
       85,  235,   85,   85,   85,   85,   85,   85,   85,   85,
      235,   85,   85,  235,  199,  211,   85,   85,  221,  203,
       85,   85,  235,  213,  235,  219,  212,  217,  220,   85,
       85,  215,  235,  214,  209,  216,  210,   85,   85,  222,

      235,  224,  218,   85,   85,   85,   85,  223,   85,   85,
       85,   85,   85,   85,   85,   85,  225,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,  226,   85,   85,
       85,   85,   85,   85,   85,   85,  235,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,  229,
       85,   85,   85,   85,  230,  227,  223,  231,  228,  232,
      224,  235,  222,  225,  235,   85,   85,   85,   85,   85,
       85,   85,   85,  235,  226,  234,   85,   85,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  233,  235,  231,  232,  235,

      235,  235,  235,  235,  235,  235,  234,   62,   62,   62,
       62,   62,   68,   68,   68,   70,  235,   70,   70,   70,
       72,   72,   72,  129,  235,  129,  235,  129,  133,  235,
      133,  133,  133,    5,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235
    } ;

static yyconst short int yy_chk[809] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    7,   22,    7,   21,
       21,   23,   22,   23,   23,    3,    4,   24,  243,   24,
       24,   29,   29,   30,   30,   31,   31,   32,   32,   33,

       33,   35,   35,   34,   34,   38,   38,   32,   31,   34,
       37,   37,   35,   30,   30,   31,   33,   32,   36,   36,
       35,  240,   34,   34,   37,   65,   38,   65,   36,   39,
       39,   40,   40,   37,   41,   41,   37,   40,   42,   42,
       45,   45,   46,   46,   47,   47,  132,   41,   39,   48,
       48,   72,   42,   50,   50,   69,   49,   49,   52,   52,
       51,   51,   53,   53,   68,   54,   54,   66,   55,   55,
       64,   56,   56,   73,   60,   57,   57,   58,   58,   47,
       46,   77,   77,   28,   45,   45,   46,   49,   47,   50,
       48,   51,   27,   52,   80,   80,   50,   86,   86,   49,

       49,   53,   56,   81,   26,   81,   81,   88,   88,   53,
       54,   55,   53,   57,   73,   20,   58,   88,   73,   87,
       87,   18,   89,   89,   17,   73,   14,   73,   89,   73,
       13,   73,   90,   90,   91,   91,   92,   92,   10,   87,
       93,   93,    9,   94,   94,   91,   95,   95,   96,   96,
        8,   90,   97,   97,   98,   98,   99,   99,    5,   92,
       94,    0,   93,  100,  100,  101,  101,  102,  102,   96,
      103,  103,  104,  104,  105,  105,    0,   98,    0,   99,
        0,  102,  100,  106,  106,    0,  101,  108,  108,  104,
      107,  107,  109,  109,  103,  105,    0,  106,  110,  110,

      107,  111,  111,  112,  112,  113,  113,  114,  114,  115,
      115,  116,  116,  117,  117,  118,  118,  119,  119,  120,
      120,  121,  121,    0,  122,  122,    0,  109,    0,  110,
        0,  108,  123,  123,  124,  124,  125,  125,    0,  112,
      126,  126,  127,  127,  111,  135,  135,    0,  134,  134,
      115,  135,  113,  114,  118,    0,  116,  136,  136,    0,
      117,    0,  120,  122,  119,  134,  121,  137,  137,    0,
      138,  138,  139,  139,    0,  124,  138,  127,  136,  126,
      123,  125,  140,  140,  141,  141,  139,  142,  142,    0,
      137,    0,  140,  143,  143,  144,  144,  145,  145,  146,

      146,  147,  147,    0,  148,  148,  141,  149,  149,  145,
      150,  150,    0,  146,  148,  151,  151,  149,    0,  144,
      152,  152,  153,  153,  147,  154,  154,  155,  155,  156,
      156,    0,  151,  157,  157,  158,  158,  152,  159,  159,
      160,  160,  161,  161,  162,  162,  163,  163,  164,  164,
      165,  165,    0,  166,  166,    0,  154,    0,  167,  167,
      168,  168,    0,  153,  157,  169,  169,  170,  170,  172,
      172,    0,  155,  159,  158,    0,  156,    0,  171,  171,
        0,  173,  173,  163,    0,  161,  160,  164,  166,  174,
      174,    0,  162,  167,  171,  173,    0,  165,  175,  175,

        0,  168,  176,  176,  177,  177,  169,  178,  178,  179,
      179,  180,  180,  174,  177,    0,  175,  181,  181,  182,
      182,  183,  183,  184,  184,  181,  179,    0,  178,    0,
      180,  185,  185,  184,  186,  186,  187,  187,  188,  188,
      185,  189,  189,  183,  190,  190,  191,  191,  192,  192,
      193,  193,  194,  194,  195,  195,  196,  196,    0,  197,
      197,    0,  198,  198,  199,  199,  200,  200,  202,  202,
        0,  201,  201,    0,  186,  187,  203,  203,  202,  190,
      204,  204,    0,  189,    0,  200,  188,  195,  201,  206,
      206,  193,    0,  192,  197,  194,  198,  205,  205,  204,

        0,  206,  196,  207,  207,  208,  208,  205,  209,  209,
      210,  210,  211,  211,  213,  213,  207,  212,  212,  214,
      214,  215,  215,  216,  216,  217,  217,  208,  218,  218,
      219,  219,  222,  222,  220,  220,    0,  221,  221,  223,
      223,  224,  224,  225,  225,  226,  226,  227,  227,  213,
      228,  228,  229,  229,  219,  211,  215,  220,  212,  221,
      216,    0,  214,  217,    0,  230,  230,  231,  231,  232,
      232,  233,  233,    0,  218,  230,  234,  234,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  227,    0,  228,  229,    0,

        0,    0,    0,    0,    0,    0,  233,  236,  236,  236,
      236,  236,  237,  237,  237,  238,    0,  238,  238,  238,
      239,  239,  239,  241,    0,  241,    0,  241,  242,    0,
      242,  242,  242,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "wardenlex.l"
#define INITIAL 0
#line 4 "wardenlex.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    int lineno = 1; // initialized number of line with 1
    int words = 0;  //number of lexemes
    void ret_print(char *token_type);
    void yyerror();
#define ML_COMMENT 1

#line 636 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 27 "wardenlex.l"


#line 790 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 236 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 734 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "wardenlex.l"
{ printf("Line is commented at line %d\n", lineno); } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "wardenlex.l"
{ printf("Start of comment from line %d ", lineno); BEGIN(ML_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "wardenlex.l"
{ printf("Ends to line %d\n", lineno); BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "wardenlex.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "wardenlex.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "wardenlex.l"
{ lineno += 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "wardenlex.l"
{ ret_print("KEYWORD_CHAR"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "wardenlex.l"
{ ret_print("KEYWORD_INT"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "wardenlex.l"
{ ret_print("KEYWORD_SINGLE"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "wardenlex.l"
{ ret_print("KEYWORD_IF"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "wardenlex.l"
{ ret_print("KEYWORD_ELSE"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "wardenlex.l"
{ ret_print("KEYWORD_WHILE"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "wardenlex.l"
{ ret_print("KEYWORD_FOR"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "wardenlex.l"
{ ret_print("KEYWORD_CONTINUE"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "wardenlex.l"
{ ret_print("KEYWORD_BREAK"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "wardenlex.l"
{ ret_print("KEYWORD_RETURN"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "wardenlex.l"
{ ret_print("KEYWORD_DEFAULT"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "wardenlex.l"
{ ret_print("KEYWORD_YIELD"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "wardenlex.l"
{ ret_print("KEYWORD_UNLESS"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "wardenlex.l"
{ ret_print("KEYWORD_DOTIMES"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "wardenlex.l"
{ ret_print("KEYWORD_SWITCH"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "wardenlex.l"
{ ret_print("KEYWORD_MAIN"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "wardenlex.l"
{ ret_print("KEYWORD_FALSE"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "wardenlex.l"
{ ret_print("KEYWORD_TRUE"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "wardenlex.l"
{ ret_print("KEYWORD_VAR"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "wardenlex.l"
{ ret_print("KEYWORD_STRING"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "wardenlex.l"
{ ret_print("KEYWORD_FUNCTION"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "wardenlex.l"
{ ret_print("KEYWORD_DO"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "wardenlex.l"
{ ret_print("KEYWORD_BOOL"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "wardenlex.l"
{ ret_print("minOP"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "wardenlex.l"
{ ret_print("ADDOP"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "wardenlex.l"
{ ret_print("MULOP"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "wardenlex.l"
{ ret_print("DIVOP"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "wardenlex.l"
{ ret_print("IINCROP"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "wardenlex.l"
{ ret_print("DINCROP"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "wardenlex.l"
{ ret_print("OROP"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "wardenlex.l"
{ ret_print("ANDOP"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "wardenlex.l"
{ ret_print("NOTOP"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "wardenlex.l"
{ ret_print("EQUOP"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "wardenlex.l"
{ ret_print("NOTEQUOP"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "wardenlex.l"
{ ret_print("GTHANOP"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "wardenlex.l"
{ ret_print("LTHANOP"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "wardenlex.l"
{ ret_print("GEQTHANOP"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "wardenlex.l"
{ ret_print("LEQTHANOP"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "wardenlex.l"
{ ret_print("EXPOP"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "wardenlex.l"
{ ret_print("MODOP"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "wardenlex.l"
{ ret_print("LPAREN"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "wardenlex.l"
{ ret_print("RPAREN"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "wardenlex.l"
{ ret_print("LBRACK"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 86 "wardenlex.l"
{ ret_print("RBRACK"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "wardenlex.l"
{ ret_print("LBRACE"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 "wardenlex.l"
{ ret_print("RBRACE"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "wardenlex.l"
{ ret_print("SEMI"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "wardenlex.l"
{ ret_print("DOT"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "wardenlex.l"
{ ret_print("COMMA"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 "wardenlex.l"
{ ret_print("ASSIGN"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 "wardenlex.l"
{ ret_print("REFER"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 95 "wardenlex.l"
{ ret_print("PREPROCESSOR DIRECTIVES"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 96 "wardenlex.l"
{ ret_print("ID"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 97 "wardenlex.l"
{ ret_print("ICONST"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 98 "wardenlex.l"
{ ret_print("FCONST"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 99 "wardenlex.l"
{ ret_print("CCONST"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 100 "wardenlex.l"
{ ret_print("STRING"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "wardenlex.l"
{ lineno += 1; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "wardenlex.l"
{ ret_print("WHITESPACE"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 104 "wardenlex.l"
{ yyerror("Unrecognized character"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "wardenlex.l"
ECHO;
	YY_BREAK
#line 1208 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 236 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 236 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 235);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 106 "wardenlex.l"

 
void ret_print(char *token_type){
    words++;
    printf("yytext: %s\ttoken: %s\tlineno: %d\n", yytext, token_type, lineno);
}
 
void yyerror(char *message){
    printf("Error: \"%s\" in line %d. Token = %s\n", message, lineno, yytext);
    exit(1);
}
 
int main(int argc, char *argv[]){
    yyin = fopen(argv[1], "r");
    yylex();
    fclose(yyin);
    printf("Number of Lexemes = %d\n", words);
    return 0;
}