/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
static yyconst short int yy_accept[199] =
    {   0,
        0,    0,    0,    0,   79,   77,   76,   75,   42,   77,
       77,   67,   50,   77,   77,   56,   57,   36,   34,   65,
       35,   64,   37,   71,   71,   62,   63,   46,   66,   45,
       69,   58,   59,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   60,   77,   61,
        4,    6,    5,   76,   44,    0,   74,    0,   70,    0,
       70,   55,   41,    0,    0,   49,   53,   38,   51,   39,
        0,   71,   52,   72,    2,    1,   54,   71,   48,   43,
       47,   69,   69,    0,   69,   69,   69,   69,   69,   69,
       27,   69,   69,   26,   69,   10,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   69,   40,
        4,    3,   74,   73,    0,   71,    1,    0,    0,   68,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   13,
        8,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       24,   69,   69,   68,   28,   69,   33,    7,   14,   69,
       69,   11,   69,   69,   21,   69,   69,   32,   69,   69,
       69,   23,   69,   29,   69,   69,   15,   69,   69,   69,
       22,   69,   30,   69,   69,   69,   69,   69,   12,   69,
       69,   69,   69,   69,   69,   16,    9,   25,   20,   18,
       28,   69,   17,   19,    8,   31,   14,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    7,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       29,   30,   31,    7,    7,    7,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   28,   41,   42,   43,   44,
       45,   46,   28,   47,   48,   49,   50,   51,   52,   28,
       28,   28,   53,   54,   55,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    2,    3,    3,    4,    4,    3,    3,    3,
        3,    3,    3,    5,    3,    3,    3,    3,    3,    6,
        6,    3,    3,    3,    3,    3,    3,    6,    7,    4,
        3,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    3,    4,    3
    } ;

static yyconst short int yy_base[208] =
    {   0,
        0,    0,   53,   54,  269,  604,   56,  604,  240,   65,
      115,  604,  237,  251,  225,  604,  604,  109,  112,  604,
      108,   41,  124,  133,    0,  604,  604,  222,  213,  203,
      121,  604,  604,  126,  120,  121,  130,  138,  144,  129,
       18,  148,  152,   19,  158,  162,   85,  604,  190,  604,
        0,  604,  194,  154,  604,  200,    0,    0,  239,  194,
      210,  604,  604,  179,  185,  604,  604,  604,  604,  604,
      158,  203,  604,  199,  604,    0,  604,    0,  604,  604,
      604,  151,  115,  169,  180,  190,  194,  201,  205,  206,
      209,  212,  221,  247,  248,  251,  252,  260,  263,  257,

      277,  267,  268,  276,  280,  284,  272,  288,  292,  320,
        0,  604,  158,  604,  137,  324,    0,  113,  289,  100,
      301,  302,  314,  306,  307,  323,  317,  322,  318,  326,
      336,  330,  335,  339,  343,  347,  351,  348,  363,  364,
      331,  367,  359,   28,  371,  372,  358,  375,  381,  380,
      386,  387,  399,  398,  392,  393,  402,  403,  409,  408,
      423,  413,  414,  418,  428,  434,  422,  427,  435,  440,
      439,  447,  446,  451,  454,  459,  463,  464,  458,  469,
      470,  474,  477,  481,  485,  486,  489,  490,  493,  494,
      497,  507,  500,  501,  504,  508,  511,  604,  558,  562,

      566,  568,  575,  580,  587,  589,  596
    } ;

static yyconst short int yy_def[208] =
    {   0,
      198,    1,  199,  199,  198,  198,  198,  198,  198,  198,
      200,  198,  198,  198,  201,  198,  198,  198,  198,  198,
      198,  198,  198,  200,   24,  198,  198,  198,  198,  198,
      202,  198,  198,  202,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,  198,   24,  198,
      203,  198,  198,  198,  198,  204,   10,   10,  204,   24,
      200,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  205,  198,   24,  198,  198,
      198,  206,   34,  207,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   24,
      203,  198,  204,  198,  198,  198,  205,  207,  207,  207,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,  207,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,    0,  198,  198,

      198,  198,  198,  198,  198,  198,  198
    } ;

static yyconst short int yy_nxt[660] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,    6,   31,   32,   11,
       33,   31,   34,   35,   36,   37,   38,   31,   31,   39,
       31,   31,   40,   31,   31,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   52,   52,   54,  120,   54,
       74,   74,   83,   83,   99,  105,   53,   53,   56,   56,
       57,   58,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   58,   58,   56,   56,   56,   56,
       56,   56,   59,   56,   58,   56,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   56,   58,   56,
       60,   60,   66,  109,   70,   71,   68,   72,   72,   83,
      120,   83,   73,   67,   60,   60,   69,   75,   60,   60,
       82,   82,   76,  120,   60,   82,   82,  114,   77,   84,
       71,   87,   78,   78,   84,   54,   90,   54,   88,   83,
       98,   83,   60,  113,   89,   91,   83,   83,   60,   93,
       85,   92,   86,   83,   83,   83,   83,   74,   74,   84,
       96,   94,   95,  100,   83,  101,   60,   97,   83,  114,
       83,  102,   83,  107,   83,  114,   83,  119,   83,  120,

      103,  106,   83,  104,   83,  113,  108,  198,   83,   60,
       60,  198,  112,   60,   60,  198,  198,  115,   74,   74,
       71,  115,  116,  116,  121,  122,   83,   81,  115,  198,
      198,  115,  124,  115,   83,  115,   83,   80,   83,  198,
       83,  123,  126,  110,  113,   83,   79,   83,  125,   83,
       83,   83,   83,   83,   65,   83,   83,  127,   83,  128,
       63,   62,  129,  198,   55,   83,   59,   83,  198,  198,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   83,   83,   83,  130,   83,   83,   83,   83,  132,

      131,   83,  133,   83,   83,  134,   83,   83,  135,   83,
      136,   83,   83,   83,  137,  138,   83,  119,  141,  144,
       83,   83,   83,   83,   83,  140,   83,  142,   83,  139,
       83,  143,   83,  146,   83,  198,   83,  198,   83,   60,
       60,   71,  145,  116,  116,   83,   83,   83,   83,  147,
       83,   83,  148,   83,  150,  149,  151,  152,   83,  198,
       83,   83,   83,   83,   83,  153,   83,   83,   83,   83,
       83,  154,   83,  155,   83,   83,   83,   83,  156,   83,
       83,   83,   83,   83,  159,   83,  158,   83,  157,   83,
      160,   83,   83,   83,   83,   83,  161,   83,  162,  163,

      165,  164,   83,   83,   83,   83,  166,   83,   83,   83,
       83,   83,  167,   83,  198,   83,   83,   83,   83,   83,
      168,   83,  198,  198,   83,   83,   83,   83,  170,  169,
       83,   83,   83,   83,  171,  172,   83,   83,   83,   83,
      198,  173,   83,   83,   83,   83,   83,   83,  174,   83,
      175,  176,   83,   83,   83,   83,  177,   83,   83,   83,
       83,  178,   83,  179,   83,  180,   83,   83,   83,   83,
      181,   83,   83,   83,   83,  183,  182,  198,   83,   83,
       83,   83,  184,   83,   83,   83,   83,  185,  198,  187,
       83,   83,   83,   83,  186,   83,  188,   83,   83,  198,

       83,  189,   83,   83,   83,   83,  198,   83,   83,   83,
       83,  190,  191,   83,   83,   83,   83,  198,   83,  192,
       83,   83,  193,   83,  194,   83,  198,  195,  196,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,  197,   83,   83,   83,   83,   83,   83,  198,
       83,   83,   83,   83,   83,   83,  198,   83,   51,   51,
       51,   51,   51,   51,   51,   61,  198,   61,   64,   64,
       64,   64,   64,   83,   83,  111,  198,  111,  111,  198,
      111,  111,   56,   56,   56,   56,   56,  117,  198,  117,
      117,  117,  117,  117,   82,   82,  118,  198,  118,  118,

      118,  118,  118,    5,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198
    } ;

static yyconst short int yy_chk[660] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    7,  144,    7,
       22,   22,   41,   44,   41,   44,    3,    4,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       11,   11,   18,   47,   21,   21,   19,   21,   21,   47,
      120,   47,   21,   18,   11,   11,   19,   23,   24,   24,
       31,   31,   23,  118,   11,   34,   34,  115,   23,   31,
       24,   35,   24,   24,   34,   54,   36,   54,   35,   83,
       40,   83,   24,  113,   35,   36,   35,   36,   11,   38,
       34,   37,   34,   40,   37,   40,   37,   71,   71,   82,
       39,   38,   38,   42,   38,   43,   24,   39,   39,   64,
       39,   43,   42,   46,   42,   65,   43,   84,   43,   84,

       43,   45,   45,   43,   45,   56,   46,   49,   46,   49,
       49,   60,   53,   60,   60,   61,   61,   65,   74,   74,
       72,   65,   72,   72,   85,   86,   85,   30,   65,   61,
       61,   65,   88,   65,   86,   65,   86,   29,   87,   61,
       87,   87,   90,   49,   59,   88,   28,   88,   89,   89,
       90,   89,   90,   91,   15,   91,   92,   91,   92,   92,
       14,   13,   93,   61,    9,   93,   59,   93,    5,    0,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   94,   95,   94,   95,   96,   97,   96,   97,   98,

       97,  100,   99,  100,   98,  100,   98,   99,  101,   99,
      102,  102,  103,  102,  103,  104,  107,  119,  107,  119,
      104,  101,  104,  101,  105,  106,  105,  108,  106,  105,
      106,  109,  108,  122,  108,    0,  109,  110,  109,  110,
      110,  116,  121,  116,  116,  121,  122,  121,  122,  123,
      124,  125,  124,  125,  126,  125,  127,  128,  123,    0,
      123,  127,  129,  127,  129,  129,  128,  126,  128,  126,
      130,  131,  130,  132,  132,  141,  132,  141,  133,  133,
      131,  133,  131,  134,  136,  134,  135,  135,  134,  135,
      137,  136,  138,  136,  138,  137,  138,  137,  139,  140,

      143,  142,  147,  143,  147,  143,  145,  139,  140,  139,
      140,  142,  146,  142,    0,  145,  146,  145,  146,  148,
      149,  148,    0,    0,  150,  149,  150,  149,  151,  150,
      151,  152,  151,  152,  153,  154,  155,  156,  155,  156,
        0,  156,  154,  153,  154,  153,  157,  158,  157,  158,
      159,  160,  160,  159,  160,  159,  161,  162,  163,  162,
      163,  163,  164,  165,  164,  166,  167,  161,  167,  161,
      168,  168,  165,  168,  165,  170,  169,    0,  166,  169,
      166,  169,  172,  171,  170,  171,  170,  173,    0,  175,
      173,  172,  173,  172,  174,  174,  176,  174,  175,    0,

      175,  177,  179,  176,  179,  176,    0,  177,  178,  177,
      178,  178,  180,  180,  181,  180,  181,    0,  182,  181,
      182,  183,  182,  183,  183,  184,    0,  184,  185,  185,
      186,  185,  186,  187,  188,  187,  188,  189,  190,  189,
      190,  191,  192,  191,  193,  194,  193,  194,  195,    0,
      195,  192,  196,  192,  196,  197,    0,  197,  199,  199,
      199,  199,  199,  199,  199,  200,    0,  200,  201,  201,
      201,  201,  201,  202,  202,  203,    0,  203,  203,    0,
      203,  203,  204,  204,  204,  204,  204,  205,    0,  205,
      205,  205,  205,  205,  206,  206,  207,    0,  207,  207,

      207,  207,  207,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical-warden.l"
#define INITIAL 0
#line 4 "lexical-warden.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    int lineno = 1;
    int words = 0;
    void ret_print(char *token_type);
    void yyerror();
    void ret_commt();
    char str[5];
    char src[20];
#define ML_COMMENT 1

#line 591 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 34 "lexical-warden.l"



#line 746 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 199 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 604 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "lexical-warden.l"
{ ret_commt("\nLine is commented at line %d\n\n", lineno); } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "lexical-warden.l"
{ ret_commt("\nStart of comment from line %d\n", lineno); BEGIN(ML_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "lexical-warden.l"
{ ret_commt("Ends to line %d\n\n", lineno); BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "lexical-warden.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "lexical-warden.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "lexical-warden.l"
{ lineno += 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "lexical-warden.l"
{ ret_print("KEYWORD_CHAR"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "lexical-warden.l"
{ ret_print("KEYWORD_INT"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "lexical-warden.l"
{ ret_print("KEYWORD_SINGLE"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "lexical-warden.l"
{ ret_print("KEYWORD_IF"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "lexical-warden.l"
{ ret_print("KEYWORD_ELSE"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "lexical-warden.l"
{ ret_print("KEYWORD_WHILE"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "lexical-warden.l"
{ ret_print("KEYWORD_FOR"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "lexical-warden.l"
{ ret_print("KEYWORD_CONTINUE"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "lexical-warden.l"
{ ret_print("KEYWORD_BREAK"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "lexical-warden.l"
{ ret_print("KEYWORD_RETURN"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "lexical-warden.l"
{ ret_print("KEYWORD_DEFAULT"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "lexical-warden.l"
{ ret_print("KEYWORD_UNLESS"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "lexical-warden.l"
{ ret_print("KEYWORD_DOTIMES"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "lexical-warden.l"
{ ret_print("KEYWORD_SWITCH"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "lexical-warden.l"
{ ret_print("RESWORD_MAIN"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "lexical-warden.l"
{ ret_print("BOOLEAN_FALSE"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "lexical-warden.l"
{ ret_print("BOOLEAN_TRUE"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "lexical-warden.l"
{ ret_print("KEYWORD_VAR"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "lexical-warden.l"
{ ret_print("KEYWORD_STRING"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "lexical-warden.l"
{ ret_print("KEYWORD_FUNCTION"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "lexical-warden.l"
{ ret_print("KEYWORD_DO"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "lexical-warden.l"
{ ret_print("KEYWORD_BOOL"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "lexical-warden.l"
{ ret_print("KEYWORD_VOID"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "lexical-warden.l"
{ ret_print("OUTPUT_STATE"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "lexical-warden.l"
{ ret_print("OUTPUTNL_STATE"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "lexical-warden.l"
{ ret_print("INPUT"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "lexical-warden.l"
{ ret_print("CASE"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "lexical-warden.l"
{ ret_print("ADDOP"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "lexical-warden.l"
{ ret_print("MINOP"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "lexical-warden.l"
{ ret_print("MULOP"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "lexical-warden.l"
{ ret_print("DIVOP"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "lexical-warden.l"
{ ret_print("IINCROP"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "lexical-warden.l"
{ ret_print("DECROP"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "lexical-warden.l"
{ ret_print("OROP"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "lexical-warden.l"
{ ret_print("ANDOP"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "lexical-warden.l"
{ ret_print("NOTOP"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "lexical-warden.l"
{ ret_print("EQUOP"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "lexical-warden.l"
{ ret_print("NOTEQUOP"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "lexical-warden.l"
{ ret_print("GTHANOP"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "lexical-warden.l"
{ ret_print("LTHANOP"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "lexical-warden.l"
{ ret_print("GEQTHANOP"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "lexical-warden.l"
{ ret_print("LEQTHANOP"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "lexical-warden.l"
{ ret_print("EXPOP"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "lexical-warden.l"
{ ret_print("MODOP"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "lexical-warden.l"
{ ret_print("ADDEQOP"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "lexical-warden.l"
{ ret_print("MINEQOP"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "lexical-warden.l"
{ ret_print("MULEQOP"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "lexical-warden.l"
{ ret_print("DIVEQOP"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "lexical-warden.l"
{ ret_print("MODEQOP"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "lexical-warden.l"
{ ret_print("LPAREN"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "lexical-warden.l"
{ ret_print("RPAREN"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "lexical-warden.l"
{ ret_print("LBRACK"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "lexical-warden.l"
{ ret_print("RBRACK"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "lexical-warden.l"
{ ret_print("LBRACEDEM"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "lexical-warden.l"
{ ret_print("RBRACEDEM"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "lexical-warden.l"
{ ret_print("COLON"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "lexical-warden.l"
{ ret_print("SEMIDEM"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "lexical-warden.l"
{ ret_print("DOT"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 107 "lexical-warden.l"
{ ret_print("COMMA"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "lexical-warden.l"
{ ret_print("ASSIGN"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "lexical-warden.l"
{ ret_print("REFERVAR"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 112 "lexical-warden.l"
{ ret_print("ARRAY"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 113 "lexical-warden.l"
{ ret_print("VALID IDENTIFIER"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 114 "lexical-warden.l"
{ ret_print("INVALID IDENTIFIER"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 115 "lexical-warden.l"
{ ret_print("ICONST"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 116 "lexical-warden.l"
{ ret_print("FCONST"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 117 "lexical-warden.l"
{ ret_print("CCONST"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 118 "lexical-warden.l"
{ ret_print("STRING"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 121 "lexical-warden.l"
{ lineno += 1; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 122 "lexical-warden.l"
;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 123 "lexical-warden.l"
{ yyerror("INVALID"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 125 "lexical-warden.l"
ECHO;
	YY_BREAK
#line 1219 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 199 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 199 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 198);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 125 "lexical-warden.l"

 

void ret_print(char *token_type){
    words++;
    printf("LineNo: %d\t Lexeme: %s\tToken: %s\n", lineno, yytext, token_type);
    fprintf(yyout,"LineNo: %d\t Lexeme: %s\tToken: %s\n", lineno, yytext, token_type);
}
 
void yyerror(char *message){
    printf("Error: \"%s\" in line %d. Token = %s\n", message, lineno, yytext);
    fprintf(yyout,"Error: \"%s\" in line %d. Lexeme = %s\n", message, lineno, yytext);
}

void ret_commt(char *message, int lineno){
    printf(message, lineno);
    fprintf(yyout, message, lineno);
}

int main(){
    extern FILE *yyin, *yyout; 

    printf("Enter Warden Source File with 'ward [sourcefile.wd]':\n");
        scanf("%s", str);
        scanf("%s", src);
        
	char search[] = "ward";
	char *ptr = strstr(str, search);

	if (ptr != NULL)
	{
		yyin = fopen(src, "r"); 
                if(yyin == NULL){
                        printf("File not detected or different file\n");
                        return 1;
                }
	}
	else
	{
		printf("\nPlease include \"ward\" then source file!\n\n");
                return 1;
	}

    yyout = fopen("Symbol Table.txt", "w+"); 
    yylex();
    printf("\n\nTotal Tokens = %d\n\n", words);
	fprintf(yyout,"\n\n\nTotal Tokens = %d",words);

    system("pause");
    return 0;
}